import { readFile, writeFile, mkdir } from 'node:fs/promises';
const config = JSON.parse(await readFile(new URL('../site.config.json', import.meta.url), 'utf8'));
const raw = process.env.SITE_URL || config.url;
const origin = raw ? new URL(raw).origin : '';
if (origin && !origin.startsWith('https://')) throw new Error('SITE_URL must use HTTPS.');
const operator = process.env.SITE_OPERATOR || config.operator;
const email = process.env.SITE_EMAIL || config.email;
const operatorUrl = config.operatorUrl || '';
const ready = Boolean(origin && operator && email && config.hostingProvider);
const esc = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const title = 'Kolik rohlíků?';
const description = 'Přepočítej koruny na rohlíky a sleduj, jak roste tvoje hora pečiva. Jednoduchá kalkulačka bez registrace.';
const image = `${origin}/og.png`;
const metadata = `${operator ? `<meta name="author" content="${esc(operator)}">` : ''}<meta name="description" content="${description}">\n<meta name="robots" content="${ready ? 'index,follow' : 'noindex,nofollow'}">\n${origin ? `<link rel="canonical" href="${origin}/">` : ''}
<meta property="og:type" content="website"><meta property="og:locale" content="cs_CZ"><meta property="og:site_name" content="${title}"><meta property="og:title" content="${title}"><meta property="og:description" content="${description}">${origin ? `<meta property="og:url" content="${origin}/">` : ''}<meta property="og:image" content="${image}"><meta property="og:image:type" content="image/png"><meta property="og:image:width" content="1734"><meta property="og:image:height" content="907"><meta property="og:image:alt" content="Kolik rohlíků? Zlatá hora rohlíků na světlém pozadí."><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${title}"><meta name="twitter:description" content="${description}"><meta name="twitter:image" content="${image}">
<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'WebApplication',name:title,...(origin?{url:origin+'/'}:{}),description,...(operator?{creator:{'@type':'Person',name:operator,...(operatorUrl?{url:operatorUrl}:{})}}:{}),applicationCategory:'UtilitiesApplication',operatingSystem:'Any',inLanguage:'cs',isAccessibleForFree:true,offers:{'@type':'Offer',price:'0',priceCurrency:'CZK'}}).replace(/</g,'\\u003c')}</script>`;
const root = new URL('../', import.meta.url);
let html = await readFile(new URL('index.html',root),'utf8');
html = html.replace(/\s*<meta name="description"[^>]*>/,'').replace(/<!-- SEO:START -->[\s\S]*?<!-- SEO:END -->/,'');
html = html.replace('</head>',`<!-- SEO:START -->\n${metadata}\n<!-- SEO:END -->\n</head>`);
await writeFile(new URL('index.html',root),html);
const info = `<h2>Provozovatel a kontakt</h2><p>${operator ? esc(operator) : 'Údaje provozovatele budou doplněny před zveřejněním.'}${email ? `<br><a href="mailto:${esc(email)}">${esc(email)}</a>` : ''}${operatorUrl ? `<br><a href="${esc(operatorUrl)}">${esc(operatorUrl.replace(/^https?:\/\//, '').replace(/\/$/, ''))}</a>` : ''}</p>`;
const terms = `<h1>Podmínky používání</h1><p>Kolik rohlíků? je bezplatná zábavná kalkulačka. Nevyžaduje účet a nic na ní nenakupujete.</p><h2>Jak výpočet funguje</h2><p>Zadanou částku dělíme cenou jednoho rohlíku. Zobrazujeme celé kusy a zbývající částku. Přednastavená cena je ukázková, nikoliv aktuální nabídka prodejce. Cenu můžete upravit. Hromada je ilustrační a její velikost neroste v přesném poměru k počtu kusů.</p><h2>Použití výsledků</h2><p>Výsledky slouží pro orientaci a zábavu. Před skutečným nákupem si ověřte cenu u prodejce. Aplikace neposkytuje finanční ani nákupní poradenství.</p><h2>Dostupnost a odpovědnost</h2><p>Aplikaci můžeme upravovat nebo její provoz ukončit. Nepřetržitou dostupnost ani bezchybnost nelze zaručit. Tím nejsou omezena práva, která podle závazných právních předpisů omezit nelze.</p>${info}`;
const privacy = `<h1>Soukromí</h1><p>Kalkulačka funguje přímo ve vašem prohlížeči. Nemá registraci, reklamní systém ani analytické nástroje.</p><h2>Zadané částky</h2><p>Částka a cena se používají k místnímu výpočtu. Aplikace je sama neposílá na server. Pokud otevřete odkaz obsahující částku v URL, tuto adresu obdrží také server, který stránku poskytuje.</p><h2>Uložení cen v zařízení</h2><p>Vaše zvolené ceny ukládáme do localStorage pod klíčem <code>kolik-rohliku-prices</code>, aby zůstaly při další návštěvě. Uložení není propojeno s účtem a nevyužívá se ke sledování. Data můžete odstranit vymazáním dat tohoto webu v nastavení prohlížeče.</p><h2>Provoz webu</h2><p>Při načtení webu hostitel technicky přijímá IP adresu, požadovanou URL a údaje prohlížeče. ${config.hostingProvider ? `Poskytovatel hostingu: ${esc(config.hostingProvider)}.` : ''} Fonty a obrázky načítáme ze stejného webu. Aplikace nenastavuje sledovací cookies.</p><h2>Vaše možnosti</h2><p>S dotazy ohledně osobních údajů se obraťte na provozovatele. Pokud dochází ke zpracování osobních údajů, můžete v rozsahu platných předpisů požadovat informace, přístup, opravu, výmaz nebo omezení a vznést námitku. Můžete také podat stížnost u <a href="https://uoou.gov.cz/">Úřadu pro ochranu osobních údajů</a>.</p>${info}`;
const legalStyle = `body{background:#f7f5ed;color:#302c22;font:16px/1.7 system-ui,sans-serif;margin:0}main{max-width:720px;padding:50px 24px 70px;margin:auto}h1{font-size:36px;line-height:1.2}h2{font-size:20px;margin-top:32px}a{color:inherit}nav{display:flex;gap:24px;font-size:14px}small{color:#706d63}`;
for (const [path,name,content] of [['podminky','Podmínky používání',terms],['soukromi','Soukromí',privacy]]) {

 await writeFile(new URL(`public/${path}.html`,root),`<!doctype html><html lang="cs"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${name} | Kolik rohlíků?</title><meta name="description" content="${name} aplikace Kolik rohlíků?"><meta name="robots" content="${ready?'index,follow':'noindex,nofollow'}">${origin?`<link rel="canonical" href="${origin}/${path}.html">`:''}<link rel="icon" href="/assets/rohliky.png"><style>${legalStyle}</style></head><body><main><nav><a href="/">← Kolik rohlíků?</a><a href="/${path==='podminky'?'soukromi':'podminky'}.html">${path==='podminky'?'Soukromí':'Podmínky'}</a></nav>${content}<p><small>Platné od 14. září 2026.</small></p></main></body></html>`);
}
const notFoundStyle = `${legalStyle}main{max-width:520px;text-align:center;padding-top:90px}.big{font-size:96px;font-weight:700;letter-spacing:-4px;line-height:1;margin:0}.big img{width:90px;height:78px;object-fit:contain;vertical-align:-14px;margin:0 4px}.lead{font-size:18px;margin:18px 0 8px}p.sub{color:#706d63;margin:0 0 34px}.home{display:inline-block;background:#302c22;color:#fffdf6;text-decoration:none;border:1px solid #302c22;border-radius:999px;padding:12px 22px;font-size:15px;font-weight:600;transition:background .18s,color .18s,border-color .18s}.home:hover{background:#fffdf6;color:#302c22;border-color:#e4dfd2}`;
await writeFile(new URL('public/404.html',root),`<!doctype html><html lang="cs"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Stránka nenalezena | Kolik rohlíků?</title><meta name="description" content="Tahle stránka neexistuje."><meta name="robots" content="noindex,follow"><link rel="icon" href="/assets/rohliky.png"><style>${notFoundStyle}</style></head><body><main><p class="big">4<img src="/assets/rohliky.png" alt="rohlík">4</p><p class="lead">Tady žádné rohlíky nejsou.</p><p class="sub">Stránka, kterou hledáš, se nám někam zakutálela.</p><a class="home" href="/">← Zpátky počítat rohlíky</a></main></body></html>`);
await writeFile(new URL('public/robots.txt',root),ready?`User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`:'User-agent: *\nDisallow: /\n');
await writeFile(new URL('public/sitemap.xml',root),`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${ready?['/','/podminky.html','/soukromi.html'].map(path=>`<url><loc>${esc(origin+path)}</loc></url>`).join(''):''}</urlset>\n`);
await writeFile(new URL('public/llms.txt',root),`# Kolik rohlíků?\n\n> Česká bezplatná kalkulačka převádějící koruny na celé rohlíky a zobrazující ilustrační horu pečiva.\n\n## Stránky\n- [Kalkulačka](${origin}/): Zadejte částku a cenu rohlíku.\n- [Podmínky](${origin}/podminky.html): Použití a omezení výpočtu.\n- [Soukromí](${origin}/soukromi.html): Místní ukládání cen a provoz webu.\n\n## Provozovatel\n${operator}\n${email}${operatorUrl ? `\n${operatorUrl}` : ''}\n\n## Přesnost\nCeny jsou nastavitelné příklady, ne živé tržní ceny. Výpočet používá celé haléře. Hromada je ilustrační, její růst je logaritmický. Aplikace neprodává potraviny a neposkytuje finanční poradenství.\n`);
await writeFile(new URL('public/site.webmanifest',root),JSON.stringify({name:title,short_name:title,lang:'cs',start_url:'/',display:'browser',background_color:'#f7f5ed',theme_color:'#f7f5ed',icons:[{src:'/assets/rohliky.png',sizes:'1254x1254',type:'image/png',purpose:'any'}]},null,2));
if (!ready) console.log('Local metadata generated. Set url, operator, email, and hostingProvider in site.config.json before launch.');
if (process.argv.includes('--check') && !ready) process.exitCode = 1;
